const CONSTANTS = {
  JOIN_ROOM: 'JOIN_ROOM',
  BOT: 'BOT',
  MESSAGE: 'MESSAGE',
  USER_JOIN: 'USER_JOIN',
  ROOM_NAME_AND_USERS: 'ROOM_NAME_AND_USERS',
  SEND_MSG: 'SEND_MSG',
};

module.exports = { CONSTANTS };
